export const HAITI_DEPARTMENTS = [
  'Artibonite',
  'Centre',
  "Grand'Anse",
  'Nippes',
  'Nord',
  'Nord-Est',
  'Nord-Ouest',
  'Ouest',
  'Sud',
  'Sud-Est',
];

export const DEPARTMENT_CITIES: Record<string, string[]> = {
  Artibonite: [
    'Dessalines',
    'Desdunes',
    'Grande-Saline',
    "Petite-Rivière-de-l'Artibonite",
    'Gonaïves',
    'Ennery',
    "L'Estère",
    'Gros-Morne',
    'Anse-Rouge',
    'Terre-Neuve',
    'Marmelade',
    "Saint-Michel-de-l'Attalaye",
    'Saint-Marc',
    'Les Arcadins',
    'La Chapelle',
    'Liancourt',
    'Verrettes',
    'Montrouis',
  ],
  Centre: [
    'Cerca-la-Source',
    'Thomassique',
    'Hinche',
    'Cerca-Carvajal',
    'Maïssade',
    'Thomonde',
    'Lascahobas',
    'Baptiste',
    'Belladère',
    'Savanette',
    'Mirebalais',
    'Boucan-Carré',
    "Saut-d'Eau",
  ],
  "Grand'Anse": [
    "Anse-d'Hainault",
    'Dame-Marie',
    'Les Irois',
    'Beaumont',
    'Corail',
    'Pestel',
    'Roseaux',
    'Abricots',
    'Bonbon',
    'Chambellan',
    'Jérémie',
    'Marfranc',
    'Moron',
  ],
  Nippes: [
    'Anse-à-Veau',
    'Arnaud',
    "L'Asile",
    'Petit-Trou-de-Nippes',
    'Plaisance-du-Sud',
    'Baradères',
    'Grand-Boucan',
    'Fonds-des-Nègres',
    'Miragoâne',
    'Paillant',
    'Petite-Rivière-de-Nippes',
  ],
  Nord: [
    'Acul-du-Nord',
    'Milot',
    'Plaine-du-Nord',
    'Borgne',
    'Port-Margot',
    'Cap-Haïtien',
    'Limonade',
    'Quartier-Morin',
    'Grande-Rivière-du-Nord',
    'Bahon',
    'Limbé',
    'Bas-Limbé',
    'Plaisance',
    'Pilate',
    'Saint-Raphaël',
    'Dondon',
    'La Victoire',
    'Pignon',
    'Ranquitte',
  ],
  'Nord-Est': [
    'Fort-Liberté',
    'Perches',
    'Ferrier',
    'Ouanaminthe',
    'Capotille',
    'Mont-Organisé',
    'Trou-du-Nord',
    'Caracol',
    'Sainte-Suzanne',
    'Grand-Bassin',
    'Terrier-Rouge',
    'Vallières',
    'Carice',
    'Mombin-Crochu',
  ],
  'Nord-Ouest': [
    'Môle-Saint-Nicolas',
    'Baie-de-Henne',
    'Bombardopolis',
    'Jean-Rabel',
    'Port-de-Paix',
    'Bassin-Bleu',
    'Chansolme',
    'Lapointe',
    'La Tortue',
    'Saint-Louis-du-Nord',
    'Anse-à-Foleur',
  ],
  Ouest: [
    'Arcahaie',
    'Cabaret',
    'Croix-des-Bouquets',
    'Cornillon',
    'Fonds-Verrettes',
    'Ganthier',
    'Thomazeau',
    'Anse-à-Galets',
    'Pointe-à-Raquette',
    'Léogâne',
    'Grand-Goâve',
    'Petit-Goâve',
    'Carrefour',
    'Delmas',
    'Gressier',
    'Kenscoff',
    'Pétion-Ville',
    'Tabarre',
    'Cité Soleil',
    'Port-au-Prince',
  ],
  Sud: [
    'Aquin',
    'Cavaillon',
    'Saint-Louis-du-Sud',
    'Fond des Blancs',
    'Les Cayes',
    'Camp-Perrin',
    'Chantal',
    'Île-à-Vache',
    'Maniche',
    'Torbeck',
    'Chardonnières',
    'Les Anglais',
    'Tiburon',
    'Les Côteaux',
    'Port-à-Piment',
    'Roche-à-Bateaux',
    'Port-Salut',
    'Arniquet',
    'Saint-Jean-du-Sud',
  ],
  'Sud-Est': [
    'Bainet',
    'Côtes-de-Fer',
    'Belle-Anse',
    'Anse-à-Pitres',
    'Grand-Gosier',
    'Thiotte',
    'Jacmel',
    'Cayes-Jacmel',
    'La Vallée-de-Jacmel',
    'Marigot',
  ],
};

export const HAITI_CITIES = Object.values(DEPARTMENT_CITIES).flat();

// Default location (Port-au-Prince)
export const DEFAULT_LOCATION = {
  latitude: 18.5944,
  longitude: -72.3074,
  latitudeDelta: 0.05,
  longitudeDelta: 0.05,
};
